INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ('John', 'Doe', '1', 'NULL')
INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ('Mike', 'Chan', '2', 'John Doe')
INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ('Ashley', 'Rodriquez', '3', 'NULL')
INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ('Kevin', 'Tupic', '4', 'Ashley Rodriquez')
INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ('Kunal', 'Singh', '5', 'NULL')
INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ('Malia', 'Brown', '6', 'Kunal Singh')
INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ('Sarah', 'Lourd', '7', 'NULL')
INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ('Tom', 'Allen', '8', 'Sarah Lourd')
INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ('Sam', 'Kash', '9', 'Ashley Rodriquez')

INSERT INTO department (department_name)
VALUES ('Account Manager')
INSERT INTO department (department_name)
VALUES ('Account Manager')
INSERT INTO department (department_name)
VALUES ('Account Manager')
INSERT INTO department (department_name)
VALUES ('Account Manager')
INSERT INTO department (department_name)
VALUES ('Account Manager')
INSERT INTO department (department_name)
VALUES ('Account Manager')
INSERT INTO department (department_name)
VALUES ('Account Manager')
INSERT INTO department (department_name)
VALUES ('Account Manager')
INSERT INTO department (department_name)
VALUES ('Account Manager')
